### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by Bonnie20402** [ProtocolSupport/ProtocolSupportPocketStuff#116]
I've tryed using it with Spigot 1.8.8 and Paperspigot 1.12.2
I always get this error: 
`> [16:37:19 INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.29-dev-pe
> [16:37:19 ERROR]: Error occurred while enabling ProtocolSupport v4.29-dev-pe (Is it up to date?)
java.lang.IllegalStateException: Access to implementation before detect
at protocolsupport.zplatform.ServerPlatform.get(ServerPlatform.java:36) ~[?:?]
at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:81) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot18.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot18.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`
Any help?

**Comment by Remu1012** [comment]
Use 1.13.2
