### ISSUE TITLE
bosbar dont work

### ISSUE THREAD

**Issue by XxKiana-kaslanaxX** [ProtocolSupport/ProtocolSupportPocketStuff#58]
``[17:02:59 WARN]: Error occured while handling packet sending
[17:02:59 WARN]: java.lang.IllegalArgumentException: Cant fit key 4 in size 4 and offset 0
[17:03:00 WARN]:        at protocolsupport.utils.CollectionsUtils$ArrayMap.put(CollectionsUtils.java:80)
[17:03:00 WARN]:        at protocolsupportpocketstuff.hacks.bossbars.BossBarPacketListener$CachedBossBar.updateMetadata(BossBarPacketListener.java:160)
[17:03:00 WARN]:        at protocolsupportpocketstuff.hacks.bossbars.BossBarPacketListener.onPacketSending(BossBarPacketListener.java:102)
[17:03:00 WARN]:        at protocolsupport.protocol.ConnectionImpl.handlePacketSend(ConnectionImpl.java:189)
[17:03:00 WARN]:        at protocolsupport.protocol.pipeline.common.LogicHandler.encode(LogicHandler.java:55)
[17:03:00 WARN]:        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[17:03:00 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[17:03:00 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[17:03:00 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[17:03:00 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[17:03:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[17:03:00 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:206)
[17:03:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:342)
[17:03:00 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[17:03:00 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[17:03:00 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[17:03:00 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[17:03:00 WARN]:        at java.lang.Thread.run(Unknown Source)``

**Comment by Speentie8081** [comment]
@XxKiana-kaslanaxX thanks for posting this, I forgot to get around to it.
