### ISSUE TITLE
pspe dont work with glowstone

### ISSUE THREAD

**Issue by Wesley-VanNeck** [ProtocolSupport/ProtocolSupportPocketStuff#65]
`[java.lang.NoClassDefFoundError:](net/minecraft/server/v1_12_R1/EntityTracker
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:130)
        at net.glowstone.GlowServer.loadPlugins(GlowServer.java:1256)
        at net.glowstone.GlowServer.start(GlowServer.java:776)
        at net.glowstone.GlowServer.run(GlowServer.java:631)
        at net.glowstone.GlowServer.main(GlowServer.java:495)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.EntityTracker
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more`

**Comment by 7kasper** [comment]
Fixed.
