### ISSUE TITLE
[PSPE] Spawning an ender dragon gives a crash loop to PE clients

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketStuff#77]
It seems that you can't beat the ender dragon with your mobile phone because chances are that you will crash before even seeing the End dimension

**Comment by 7kasper** [comment]
Any console errors?

**Comment by Wesley-VanNeck** [comment]
@7kasper its a client crash

**Comment by magicus** [comment]
I can confirm this. Client is immediately kicked out when the dragon is summoned. Here's the log I got:

```
[11:48:02 INFO]: mag_icus issued server command: /summon minecraft:ender_dragon
[11:48:02 WARN]: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.07.14 at 11:40:14 CEST, buildhost: unknown, buildnumber: unknown)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.protocol.utils.authlib.GameProfile(onlineMode: false, originalname: magicusse, originaluuid: b38060ce-b4c6-3fde-bcaa-1839032ac1dd, name: magicusse, uuid: b38060ce-b4c6-3fde-bcaa-1839032ac1dd, properties: {}), player: CraftPlayer{name=magicusse}, address: /192.168.8.106:52579, rawaddress: /127.0.0.1:62007, version: MINECRAFT_PE, metadata: {___PS_PE_XUID=2535422216410906}))
[11:48:02 WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.exceptionCaught(LogicHandler.java:62)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 INFO]: [mag_icus: Object successfully summoned]
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
[11:48:02 WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1401)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
[11:48:02 WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:953)
[11:48:02 WARN]: 	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
[11:48:02 WARN]: 	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
[11:48:02 WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[11:48:02 WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
[11:48:02 WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[11:48:02 WARN]: 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
[11:48:02 WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[11:48:02 WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[11:48:02 WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:206)
[11:48:02 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[11:48:02 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[11:48:02 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[11:48:02 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[11:48:02 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11:48:02 WARN]: Caused by: io.netty.handler.codec.EncoderException: Unable to transform or read packet data [3, -126, 5, 61, 64, 51, 8, 52, -9, 67, -99, -126, 71, 87, 103, 118, 67, -11, -54, 63, 64, 41, -125, -45, -112, -16, 119, -110, 64, 80, -123, 70, 40, 120, 108, -95, 64, 112, 51, -102, -114, -106, -23, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 3, 0, 3, 6, 0, 4, 6, 0, 5, 6, 0, 6, 0, 0, 7, 2, 67, 72, 0, 0, 8, 1, 0, 9, 6, 0, 10, 1, 0, 11, 0, 0, 12, 1, 10, -1]
[11:48:02 WARN]: 	at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:59)
[11:48:02 WARN]: 	at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:24)
[11:48:02 WARN]: 	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:37)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[11:48:02 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[11:48:02 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[11:48:02 WARN]: 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[11:48:02 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[11:48:02 WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:200)
[11:48:02 WARN]: 	... 5 more
[11:48:02 WARN]: Caused by: java.lang.NullPointerException
[11:48:02 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.remapper.SpecificRemapper$1.remap(SpecificRemapper.java:102)
[11:48:02 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.DataWatcherDataRemapper.lambda$remap$0(DataWatcherDataRemapper.java:27)
[11:48:02 WARN]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[11:48:02 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.DataWatcherDataRemapper.remap(DataWatcherDataRemapper.java:27)
[11:48:02 WARN]: 	at protocolsupport.protocol.typeremapper.watchedentity.DataWatcherDataRemapper.init(DataWatcherDataRemapper.java:21)
[11:48:02 WARN]: 	at protocolsupport.protocol.packet.middle.clientbound.play.MiddleSpawnLiving.readFromServerData(MiddleSpawnLiving.java:42)
[11:48:02 WARN]: 	at protocolsupport.protocol.pipeline.version.util.encoder.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:45)
[11:48:02 WARN]: 	... 26 more
[11:48:02 WARN]: java.nio.channels.ClosedChannelException
[11:48:02 WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[11:48:03 INFO]: magicusse lost connection: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.07.14 at 11:40:14 CEST, buildhost: unknown, buildnumber: unknown)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.protocol.utils.authlib.GameProfile(onlineMode: false, originalname: magicusse, originaluuid: b38060ce-b4c6-3fde-bcaa-1839032ac1dd, name: magicusse, uuid: b38060ce-b4c6-3fde-bcaa-1839032ac1dd, properties: {}), player: CraftPlayer{name=magicusse}, address: /192.168.8.106:52579, rawaddress: /127.0.0.1:62007, version: MINECRAFT_PE, metadata: {___PS_PE_XUID=2535422216410906}))
[11:48:03 INFO]: magicusse left the game
[11:48:15 INFO]: [ProtocolSupport] /127.0.0.1:62086 connected with protocol version MINECRAFT_PE
[11:48:17 INFO]: [ProtocolSupport] /127.0.0.1:62087 connected with protocol version MINECRAFT_PE
[11:48:18 INFO]: [ProtocolSupport] /127.0.0.1:62089 connected with protocol version MINECRAFT_PE
[11:48:20 INFO]: [ProtocolSupport] /127.0.0.1:62091 connected with protocol version MINECRAFT_PE
[11:48:22 INFO]: [ProtocolSupport] /127.0.0.1:62094 connected with protocol version MINECRAFT_PE
[11:48:27 INFO]: [ProtocolSupport] /127.0.0.1:62095 connected with protocol version MINECRAFT_PE
[11:48:28 INFO]: [ProtocolSupport] /127.0.0.1:62096 connected with protocol version MINECRAFT_PE
[11:48:30 INFO]: [ProtocolSupport] /127.0.0.1:62097 connected with protocol version MINECRAFT_PE
[11:48:31 INFO]: [ProtocolSupport] /127.0.0.1:62098 connected with protocol version MINECRAFT_PE
[11:48:33 INFO]: [ProtocolSupport] /127.0.0.1:62099 connected with protocol version MINECRAFT_PE
```

**Comment by magicus** [comment]
I assume the relevant part is `io.netty.handler.codec.EncoderException: Unable to transform or read packet data [3, -126, 5, 61, 64, 51, 8, 52, -9, 67, -99, -126, 71, 87, 103, 118, 67, -11, -54, 63, 64, 41, -125, -45, -112, -16, 119, -110, 64, 80, -123, 70, 40, 120, 108, -95, 64, 112, 51, -102, -114, -106, -23, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 3, 0, 3, 6, 0, 4, 6, 0, 5, 6, 0, 6, 0, 0, 7, 2, 67, 72, 0, 0, 8, 1, 0, 9, 6, 0, 10, 1, 0, 11, 0, 0, 12, 1, 10, -1]`.

**Comment by caoli5288** [comment]
It's because of ender dragon missing in entitydata.json
